name: GitHub Actions Demo App

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Test On PR
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_15.3.app

    - name: Build
      run: xcodebuild -scheme ArticleSearcher -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'

    - name: Run Tests
      run: xcodebuild -scheme ArticleSearcher -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' test